export interface Client{
    IDCLIENTE?:  number,
    NOMEFANTASIA: string,
    NOME: string,
    CGCCFO: string,
    INSCRESTADUAL: string,
    PAGREC:number,
    RUA:string,
    NUMERO:string,
    COMPLEMENTO:string,
    BAIRRO :string,
    CIDADE :string,
    CODETD :string,
    CEP :string,
    TELEFONE :string,
    
    RUAPGTO :string,
    NUMEROPGTO :string,
    COMPLEMENTOPGTO :string,
    BAIRROPGTO :string,
    CIDADEPGTO :string,
    CODETDPGTO :string,
    CEPPGTO :string,
    TELEFONEPAGTO :string,
    
    RUAENTREGA :string,
    NUMEROENTREGA :string,
    COMPLEMENTOENTREGA :string,
    BAIRROENTREGA :string,
    CIDADEENTREGA :string,
    CODETDENTREGA :string,
    CEPENTREGA :string,
    TELEFONEENTREGA :string,
    
    EMAIL :string,
    ATIVO :number,
    INSCRMUNICIPAL :string,
    PESSOAFISOUJUR :string,
    PAIS :string,
    PAISPGTO :string,
    PAISENTREGA :string,
    EMAILENTREGA :string,
    EMAILPGTO :string,
    
    CODMUNICIPIOPGTO :string,
    CODMUNICIPIOENTREGA :string,
    DTCRIACAO :string,
    DTMODIFICACAO :string,
    USUARIOCRIACAO :string,
    USUARIOALTERACAO :string,
    TIPOCLIENTE :string,
}
export interface CreateClient{
    idcliente?:number
    nomefantasia: string,
    nome: string,
    cgccfo: string,
    inscrestadual: string,
    pagrec:number,
    rua:string,
    numero:string,
    complemento:string,
    bairro :string,
    cidade :string,
    codetd :string,
    cep :string,
    telefone :string,
    
    ruapgto :string,
    numeropgto :string,
    complementopgto :string,
    bairropgto :string,
    cidadepgto :string,
    codetdpgto :string,
    ceppgto :string,
    telefonepgto :string,
    
    ruaentrega :string,
    numeroentrega :string,
    complementoentrega :string,
    bairroentrega :string,
    cidadeentrega :string,
    codetdentrega :string,
    cepentrega :string,
    telefoneentrega :string,
    
    email :string,
    ativo :number,
    inscrmunicipal :string,
    pessoafisoujur :string,
    pais :string,
    paispgto :string,
    paisentrega :string,
    emailentrega :string,
    emailpgto :string,
    
    codmunicipiopgto :string,
    codmunicipioentrega :string,
    dtcriacao :string,
    dtmodificacao :string,
    usuariocriacao :string,
    usuarioalteracao :string,
    tipocliente :string,
}



// export type CreateClient = Omit<Client,"IDCLIENTE">;